"use client";

import { FormEvent, useEffect, useMemo, useState } from "react";
import { request } from "../lib/api";
import styles from "./TaskOrchestrationPanel.module.css";

type Node = { id:number; title:string; status:string; agent_role:string; parent_task_id?:number|null; depends_on:number[]; children:number[]; worktree_branch:string; pr_number:number; pr_state:string; result?:string; error?:string };
type Graph = { project_id:number; nodes:Node[] };
type ReviewItem = { id:number; title:string; agent_role:string; status:string; depends_on:number[]; worktree_branch:string; pull_request_number:number; pull_request_state:string; result?:string; error?:string; branch?:{branch_diff:string;working_diff:string;changes:string[]}|null; branch_error?:string };
type ReviewBundle = { task_id:number; base:string; items:ReviewItem[] };
type Draft = { title:string; prompt:string; role:string; parent:string; dependencies:string };
type LeadDraft = { title:string; objective:string; maxTasks:number };
type LeadResponse = { lead:Node; specialists:unknown[]; reviewer:unknown; plan:{title:string;role:string;prompt:string;depends_on:number[]}[] };
type IntegrationState = { lead_task_id:number; path:string; branch:string; base:string; diff?:string; changes?:string[]; check_command?:string; check_status?:string; check_output?:string; pull_request_number?:number; pull_request_url?:string; pull_request_state?:string };
type IntegrationPreflight = { lead_task_id:number; task_ids:number[]; base:string; branches:string[]; files_by_branch:Record<string,string[]>; overlaps:{path:string;branches:string[]}[] };

export function TaskOrchestrationPanel({ projectId, onCreated }: { projectId:number; onCreated:()=>void }) {
  const [graph,setGraph]=useState<Graph>({project_id:projectId,nodes:[]});
  const [review,setReview]=useState<ReviewBundle|null>(null);
  const [draft,setDraft]=useState<Draft>({title:"",prompt:"",role:"worker",parent:"",dependencies:""});
  const [leadDraft,setLeadDraft]=useState<LeadDraft>({title:"",objective:"",maxTasks:6});
  const [lastPlan,setLastPlan]=useState<LeadResponse["plan"]>([]);
  const [selectedLead,setSelectedLead]=useState<number|null>(null);
  const [selectedTasks,setSelectedTasks]=useState<number[]>([]);
  const [integration,setIntegration]=useState<IntegrationState|null>(null);
  const [preflight,setPreflight]=useState<IntegrationPreflight|null>(null);
  const [checkCommand,setCheckCommand]=useState("python -m pytest backend/tests -q && cd frontend && npx tsc --noEmit && npm run build");
  const [prTitle,setPrTitle]=useState("");
  const [prBody,setPrBody]=useState("Integrated and validated by Olladex multi-agent orchestration.");
  const [notice,setNotice]=useState("");
  const [busy,setBusy]=useState(false);

  useEffect(()=>{ load(); const timer=window.setInterval(load,3000); return()=>window.clearInterval(timer); },[projectId]);
  async function load(){ try{ setGraph(await request<Graph>(`/projects/${projectId}/orchestration`)); }catch(error){ setNotice(error instanceof Error?error.message:String(error)); } }

  const roots=useMemo(()=>graph.nodes.filter(node=>!node.parent_task_id),[graph.nodes]);
  const byId=useMemo(()=>new Map(graph.nodes.map(node=>[node.id,node])),[graph.nodes]);
  const integrationChildren=useMemo(()=>selectedLead?graph.nodes.filter(node=>node.parent_task_id===selectedLead&&node.agent_role!=="reviewer"):[],[graph.nodes,selectedLead]);

  async function createLead(event:FormEvent){ event.preventDefault(); if(!leadDraft.objective.trim())return; setBusy(true);setNotice("");setLastPlan([]); try{ const created=await request<LeadResponse>(`/projects/${projectId}/orchestration/lead`,{method:"POST",body:JSON.stringify({objective:leadDraft.objective.trim(),title:leadDraft.title.trim(),max_tasks:leadDraft.maxTasks})}); setLastPlan(created.plan||[]);setLeadDraft({title:"",objective:"",maxTasks:6});setNotice(`Lead task created with ${created.plan.length} specialist tasks and a final reviewer`);await load();onCreated(); }catch(error){setNotice(error instanceof Error?error.message:String(error));}finally{setBusy(false);} }
  async function createTask(event:FormEvent){ event.preventDefault();if(!draft.prompt.trim())return;const dependencies=draft.dependencies.split(",").map(item=>Number(item.trim())).filter(item=>Number.isInteger(item)&&item>0);setBusy(true);setNotice("");try{await request(`/projects/${projectId}/orchestration/tasks`,{method:"POST",body:JSON.stringify({title:draft.title.trim(),prompt:draft.prompt.trim(),agent_role:draft.role.trim()||"worker",parent_task_id:draft.parent?Number(draft.parent):null,depends_on:dependencies})});setDraft({title:"",prompt:"",role:"worker",parent:"",dependencies:""});setNotice("Orchestrated task queued");await load();onCreated();}catch(error){setNotice(error instanceof Error?error.message:String(error));}finally{setBusy(false);} }
  async function loadReview(taskId:number){setBusy(true);setNotice("");try{setReview(await request<ReviewBundle>(`/tasks/${taskId}/review-bundle`));}catch(error){setNotice(error instanceof Error?error.message:String(error));}finally{setBusy(false);} }
  async function openIntegration(lead:Node){setSelectedLead(lead.id);setPreflight(null);setSelectedTasks([]);setPrTitle(`Integrate: ${lead.title}`);try{setIntegration(await request<IntegrationState>(`/tasks/${lead.id}/integration`));}catch{setIntegration(null);} }
  function toggleIntegrationTask(id:number){setSelectedTasks(current=>current.includes(id)?current.filter(item=>item!==id):[...current,id]);}
  async function preflightIntegration(){if(!selectedLead||!selectedTasks.length)return;setBusy(true);setNotice("");try{const result=await request<IntegrationPreflight>(`/tasks/${selectedLead}/integration/preflight`,{method:"POST",body:JSON.stringify({task_ids:selectedTasks,base:"main"})});setPreflight(result);setNotice(result.overlaps.length?`${result.overlaps.length} overlapping file(s) need review`:"No file overlaps detected");}catch(error){setNotice(error instanceof Error?error.message:String(error));}finally{setBusy(false);} }
  async function createIntegration(){if(!selectedLead||!selectedTasks.length)return;setBusy(true);setNotice("");try{const result=await request<IntegrationState>(`/tasks/${selectedLead}/integration`,{method:"POST",body:JSON.stringify({task_ids:selectedTasks,base:"main"})});setIntegration(result);setNotice(`Created ${result.branch}`);}catch(error){setNotice(error instanceof Error?error.message:String(error));}finally{setBusy(false);} }
  async function runChecks(){if(!selectedLead||!checkCommand.trim())return;setBusy(true);setNotice("");try{const result=await request<{passed:boolean;output:string;command:string}>(`/tasks/${selectedLead}/integration/checks`,{method:"POST",body:JSON.stringify({command:checkCommand.trim()})});setIntegration(current=>current?{...current,check_command:result.command,check_status:result.passed?"passed":"failed",check_output:result.output}:current);setNotice(result.passed?"Combined checks passed":"Combined checks failed");}catch(error){setNotice(error instanceof Error?error.message:String(error));}finally{setBusy(false);} }
  async function pushIntegration(){if(!selectedLead)return;setBusy(true);setNotice("");try{const result=await request<{branch:string}>(`/tasks/${selectedLead}/integration/push`,{method:"POST",body:JSON.stringify({remote:"origin"})});setNotice(`Pushed ${result.branch}`);}catch(error){setNotice(error instanceof Error?error.message:String(error));}finally{setBusy(false);} }
  async function createIntegrationPr(){if(!selectedLead||!prTitle.trim())return;setBusy(true);setNotice("");try{const result=await request<{url:string;pull_request_number:number}>(`/tasks/${selectedLead}/integration/pull-request`,{method:"POST",body:JSON.stringify({title:prTitle.trim(),body:prBody,base:"main"})});setIntegration(current=>current?{...current,pull_request_number:result.pull_request_number,pull_request_url:result.url,pull_request_state:"OPEN"}:current);setNotice(`Final integration PR #${result.pull_request_number} created`);}catch(error){setNotice(error instanceof Error?error.message:String(error));}finally{setBusy(false);} }

  function statusClass(status:string){return status==="completed"?styles.statusCompleted:status==="running"||status==="coordinating"?styles.statusRunning:status==="failed"?styles.statusFailed:"";}
  function renderRoot(node:Node){const children=node.children.map(id=>byId.get(id)).filter(Boolean) as Node[];return <article key={node.id} className={styles.root}><div className={styles.rootHead}><div className={styles.rootTitle}><strong>#{node.id} {node.title}</strong><div className={styles.meta}><span className={`${styles.chip} ${statusClass(node.status)}`}>{node.status}</span><span className={styles.chip}>{node.agent_role}</span>{node.worktree_branch&&<span className={styles.chip}>{node.worktree_branch}</span>}{node.pr_number>0&&<span className={styles.chip}>PR #{node.pr_number} {node.pr_state||""}</span>}</div></div><div className={styles.rootActions}><button type="button" disabled={busy} onClick={()=>loadReview(node.id)}>Review</button>{node.agent_role==="lead"&&<button type="button" className="primary" disabled={busy} onClick={()=>openIntegration(node)}>Integrate</button>}</div></div>{children.length>0&&<div className={styles.children}>{children.map(child=><div key={child.id} className={styles.child}><div><strong>#{child.id} {child.title}</strong><small>{child.agent_role}{child.depends_on.length?` · after ${child.depends_on.map(id=>`#${id}`).join(", ")}`:""}{child.worktree_branch?` · ${child.worktree_branch}`:""}</small>{child.error&&<small>{child.error}</small>}</div><span className={`${styles.childStatus} ${statusClass(child.status)}`}>{child.status}</span></div>)}</div>}{node.agent_role==="lead"&&node.result&&<details className={styles.result}><summary>Lead consolidation result</summary><pre>{node.result}</pre></details>}</article>;}

  return <section className={styles.panel}>
    <div className={styles.hero}><div><p className="eyebrow">Multi-agent orchestration</p><h3>Coordinate larger work</h3><p>Start with one objective. Olladex breaks it into specialist tasks, waits for dependencies, then gives you a review and integration path.</p></div><span className={styles.count}>{graph.nodes.length} tasks</span></div>

    <section className={styles.stage}>
      <div className={styles.stageHead}><span className={styles.stageNo}>1</span><div><strong>Start work</strong><small>Describe the outcome you want. Olladex plans the specialists.</small></div></div>
      <form onSubmit={createLead} className={styles.leadForm}>
        <label>Title<input value={leadDraft.title} onChange={event=>setLeadDraft(current=>({...current,title:event.target.value}))} placeholder="Optional plan title" /></label>
        <label>Specialists<select value={leadDraft.maxTasks} onChange={event=>setLeadDraft(current=>({...current,maxTasks:Number(event.target.value)}))}>{[2,3,4,5,6,7,8,9,10].map(value=><option key={value} value={value}>{value}</option>)}</select></label>
        <label className={styles.objective}>Objective<textarea value={leadDraft.objective} onChange={event=>setLeadDraft(current=>({...current,objective:event.target.value}))} placeholder="Example: Add persistent application settings, update the UI, and cover it with tests." /></label>
        <div className={styles.leadActions}><button className="primary" disabled={busy||!leadDraft.objective.trim()}>{busy?"Planning…":"Start autonomous lead"}</button></div>
      </form>
      {lastPlan.length>0&&<details className={styles.plan} open><summary>Generated plan · {lastPlan.length} specialist tasks</summary><div className={styles.planList}>{lastPlan.map((item,index)=><div className={styles.planItem} key={`${index}-${item.title}`}><strong>{index+1}. {item.title}</strong><small>{item.role}{item.depends_on.length?` · after ${item.depends_on.map(dep=>dep+1).join(", ")}`:" · can start immediately"}</small><p>{item.prompt}</p></div>)}</div></details>}
      <details className={styles.advanced}><summary>Advanced · add a specialist manually</summary><form onSubmit={createTask} className={styles.advancedForm}><label>Title<input value={draft.title} onChange={event=>setDraft(current=>({...current,title:event.target.value}))}/></label><label>Role<select value={draft.role} onChange={event=>setDraft(current=>({...current,role:event.target.value}))}><option value="worker">Worker</option><option value="frontend">Frontend</option><option value="backend">Backend</option><option value="researcher">Researcher</option><option value="reviewer">Reviewer</option><option value="tester">Tester</option></select></label><label>Parent<select value={draft.parent} onChange={event=>setDraft(current=>({...current,parent:event.target.value}))}><option value="">No parent</option>{graph.nodes.map(node=><option key={node.id} value={node.id}>#{node.id} {node.title}</option>)}</select></label><label>Depends on<input value={draft.dependencies} onChange={event=>setDraft(current=>({...current,dependencies:event.target.value}))} placeholder="12, 13"/></label><label className={styles.advancedPrompt}>Task prompt<textarea value={draft.prompt} onChange={event=>setDraft(current=>({...current,prompt:event.target.value}))}/></label><button className="primary" disabled={busy||!draft.prompt.trim()}>{busy?"Working…":"Queue specialist"}</button></form></details>
    </section>

    <section className={styles.stage}>
      <div className={styles.stageHead}><span className={styles.stageNo}>2</span><div><strong>Active plans</strong><small>Follow progress here. Open Review or Integrate only when you need the next action.</small></div></div>
      <div className={styles.roots}>{roots.length?roots.map(renderRoot):<div className={styles.empty}>No orchestration plans yet. Start with an objective above.</div>}</div>
    </section>

    {(selectedLead||review)&&<section className={styles.stage}><div className={styles.stageHead}><span className={styles.stageNo}>3</span><div><strong>Review & integrate</strong><small>Combine completed specialist branches, validate once, then create the final PR.</small></div></div>
      {selectedLead&&<div className={styles.integrationBody}><div className={styles.taskSelect}>{integrationChildren.map(node=><label key={node.id}><input type="checkbox" checked={selectedTasks.includes(node.id)} disabled={node.status!=="completed"||!node.worktree_branch} onChange={()=>toggleIntegrationTask(node.id)}/><span>#{node.id} {node.title} · {node.status}</span></label>)}</div><div className={styles.actions}><button type="button" disabled={busy||!selectedTasks.length} onClick={preflightIntegration}>Check overlaps</button><button type="button" className="primary" disabled={busy||!selectedTasks.length} onClick={createIntegration}>Build integration branch</button></div>{preflight&&<div className={styles.overlap}>{preflight.overlaps.length?`${preflight.overlaps.length} overlapping file(s): ${preflight.overlaps.map(item=>item.path).join(", ")}`:"No overlapping files detected."}</div>}{integration?.branch&&<><div><strong>{integration.branch}</strong></div>{integration.diff&&<pre>{integration.diff}</pre>}<label>Combined check command<input value={checkCommand} onChange={event=>setCheckCommand(event.target.value)}/></label><div className={styles.actions}><button type="button" disabled={busy||!checkCommand.trim()} onClick={runChecks}>Run checks</button><span className={`${styles.chip} ${integration.check_status==="passed"?styles.statusCompleted:integration.check_status==="failed"?styles.statusFailed:""}`}>{integration.check_status||"not tested"}</span></div>{integration.check_output&&<pre>{integration.check_output}</pre>}<label>Final PR title<input value={prTitle} onChange={event=>setPrTitle(event.target.value)}/></label><label>Final PR description<textarea value={prBody} onChange={event=>setPrBody(event.target.value)}/></label><div className={styles.actions}><button type="button" disabled={busy||integration.check_status!=="passed"} onClick={pushIntegration}>Push integration</button><button type="button" className="primary" disabled={busy||integration.check_status!=="passed"||!prTitle.trim()} onClick={createIntegrationPr}>Create final PR</button>{integration.pull_request_url&&<button type="button" onClick={()=>window.open(integration.pull_request_url,"_blank","noopener,noreferrer")}>Open PR #{integration.pull_request_number}</button>}</div></>}</div>}
      {review&&<details className={styles.review} open><summary>Review bundle · lead #{review.task_id} · {review.items.length} items</summary>{review.items.map(item=><article key={item.id}><header><strong>#{item.id} {item.title}</strong><small>{item.agent_role} · {item.status}</small></header>{item.result&&<p>{item.result}</p>}{item.error&&<p>{item.error}</p>}{item.branch?<pre>{item.branch.working_diff||item.branch.branch_diff||"No diff"}</pre>:<p>No worktree available.</p>}</article>)}</details>}
    </section>}

    {notice&&<div className={styles.notice}>{notice}</div>}
  </section>;
}
